apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RegoConstraintTemplateNoHostNetwork
metadata:
  name: rego-constraintnohostnetwork
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
