apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RegoConstraintTemplateNoHostPath
metadata:
  name: rego-constraintnohostpath 
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        # Replicas is not matched due to testing purpose 
        kinds: ["DaemonSet", "Deployment"]
