apiVersion: constraints.gatekeeper.sh/v1beta1
kind: CELConstraintTemplateNoHostNetwork
metadata:
  name: cel-constraintnohostnetwork
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
