apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-rollingupdate-maxsurge80
  name: deploy-rollingupdate-maxsurge80
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deploy-rollingupdate-maxsurge80 
  strategy:
    rollingUpdate:
      maxSurge: 80% 
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: deploy-rollingupdate-maxsurge80 
    spec:
      containers:
      - name: nginx-max80
        image: quay.io/nginx/nginx-unprivileged:1.26.2 
        ports:
        - containerPort: 8080

