# ============================================================
# Stage 3 Test: Preferred NodeAffinity (Preference)
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: stage3-preferred-nodeaffinity
  labels:
    test: stage3-score
    component: node-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100  # Strongly prefer zone-a (w1, w2)
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - zone-a
      - weight: 80   # Moderately prefer zone-c (w5, w6)
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - zone-c
      - weight: 50   # Slightly prefer SSD (w1, w3, w5)
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
  containers:
  - name: app
    image: quay.io/nginx/nginx-unprivileged:1.27.5-alpine-slim
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
