apiVersion: v1
kind: Pod
metadata:
  labels:
    run: po-imagepullpolicy-ifnotpresent-w-tag
  name: po-imagepullpolicy-ifnotpresent-w-tag
spec:
  containers:
  - image: sysnet4admin/kubecon-eu:swp-img
    imagePullPolicy: IfNotPresent 
    name: nginx
  nodeName: w2-k8s

