# -*- mode: ruby -*-
# vi: set ft=ruby :

## configuration variables ###
########### name   m_ip w_ip #
cl_val = [["bk8s", 110, 11,2],
          ["hk8s", 120, 12,1],
          ["wk8s", 130, 13,1]]
# each of components to install 
k8s_V = '1.20.4-00'            # Kubernetes 
docker_V = '5:20.10.8~3-0~ubuntu-focal' # Docker  
ctrd_V = '1.4.9-1'    # Containerd 
## /configuration variables ###

Vagrant.configure("2") do |config|

  cl_val.each do |cv|
  
  #=============#
  # master node #
  #=============#

    config.vm.define "#{cv[0]}-m" do |cfg|
      cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "#{cv[0]}-m(github_SysNet4Admin)"
        vb.cpus = 2
        vb.memory = 1758 # a little consumed more 
        vb.customize ["modifyvm", :id, "--groups", "/cka-cluster(github_SysNet4Admin)"]
      end
      cfg.vm.host_name = "#{cv[0]}-m"
      cfg.vm.network "private_network", ip: "192.168.1.#{cv[1]}"
      cfg.vm.network "forwarded_port", guest: 22, host: "60#{cv[1]}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
      cfg.vm.provision "shell", path: "k8s_env_build.sh"
      cfg.vm.provision "shell", path: "k8s_pkg_cfg.sh", args: [ k8s_V, docker_V, ctrd_V ]
      cfg.vm.provision "shell", path: "master_node.sh", args: [ cv[1], cv[0] ]
    end
  
  #=============#
  # worker node #
  #=============#

    (1..cv[3]).each do |i|
      config.vm.define "#{cv[0]}-w#{i}" do |cfg|
        cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
        cfg.vm.provider "virtualbox" do |vb|
          vb.name = "#{cv[0]}-w#{i}(github_SysNet4Admin)"
          vb.cpus = 1
          vb.memory = 1024
          vb.customize ["modifyvm", :id, "--groups", "/cka-cluster(github_SysNet4Admin)"]
        end
        cfg.vm.host_name = "#{cv[0]}-w#{i}"
        cfg.vm.network "private_network", ip: "192.168.1.#{cv[2]}#{i}"
        cfg.vm.network "forwarded_port", guest: 22, host: "60#{cv[2]}#{i}", auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "k8s_env_build.sh"
        cfg.vm.provision "shell", path: "k8s_pkg_cfg.sh", args: [ k8s_V, docker_V, ctrd_V ]
        cfg.vm.provision "shell", path: "work_nodes.sh", args: [ cv[1], "#{cv[2]}#{i}" ]
      end
    end
  end

  #==============#
  # Console Node #
  #==============#

  config.vm.define "10cka-con" do |cfg|
    cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "10cka-con(github_SysNet4Admin)"
      vb.cpus = 1
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--groups", "/cka-cluster(github_SysNet4Admin)"]
    end
    cfg.vm.host_name = "10cka-con"
    cfg.vm.network "private_network", ip: "192.168.1.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "console.sh", args: [ k8s_V, "#{cl_val[0][1]}", "#{cl_val[1][1]}", "#{cl_val[2][1]}" ]
  end

end