apiVersion: v1
kind: Pod
metadata:
  labels:
    run: po-imagepullpolicy-ifnotpresent
  name: po-imagepullpolicy-ifnotpresent
spec:
  containers:
  - image: nginx:stable-alpine-slim
    imagePullPolicy: IfNotPresent 
    name: nginx
  nodeName: w2-k8s

