# ============================================================
# Stage 2 Test: Filter by Required PodAntiAffinity
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: stage2-pod-antiaffinity-1
  labels:
    test: stage2-filter
    component: pod-antiaffinity
    app: web
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: web
        topologyKey: kubernetes.io/hostname  # No app=web Pods on same host
  containers:
  - name: app
    image: quay.io/nginx/nginx-unprivileged:1.27.5-alpine-slim
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
