apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: yamlclusterpolicynohostnetwork
spec:
  validationFailureAction: Enforce
  rules:
  - name: YamlClusterPolicyNoHostNetwork
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "HostNetwork is not allowed for the Pod"
      pattern:
        spec:
          =(hostNetwork): "false"
