apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-default-rollingupdate-maxsurge25
  name: deploy-default-rollingupdate-maxsurge25
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deploy-default-rollingupdate-maxsurge25 
  template:
    metadata:
      labels:
        app: deploy-default-rollingupdate-maxsurge25 
    spec:
      containers:
      - name: nginx-max25
        image: quay.io/nginx/nginx-unprivileged:1.26.2 
        ports:
        - containerPort: 8080
