apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-default-rollingUpdate-maxsurge25
  name: deploy-default-rollingUpdate-maxsurge25
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deploy-default-rollingUpdate-maxsurge25 
  template:
    metadata:
      labels:
        app: deploy-default-rollingUpdate-maxsurge25 
    spec:
      containers:
      - name: nginx-max25
        image: nginx:1.26.2 

